### logging.level.root=DEBUG

spring:
  application:
    name: websocket-server
  # ?? RedisProperties ?
  data:
    redis:
      host: 192.168.92.129
      port: 6379
      password: # Redis ???????????????????? Redis ???
      database: 0 # Redis ???????? 0 ?
      timeout: 0 # Redis ?????????????
      # ?? RedisProperties.Jedis ???
      jedis:
        pool:
          max-active: 20 # ???????????? 8 ????????????
          max-idle: 8 # ????????????????? 8 ????????????
          min-idle: 0 # ????????????????? 0 ????? 0 ? ???
          max-wait: -1 # ????????????????????? -1 ???????