### logging.level.root=DEBUG


spring:
  rabbitmq:
    host: 172.16.23.77
    port: 5672
    username: admin
    password: 123456
    stomp:
      port: 61613
  thymeleaf:
    cache: false
  application:
    name: websocket-server
  main:
    allow-circular-references: true
server:
  port: 8080
